---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petrosa-binance-data-extractor-config
  namespace: petrosa-apps
  labels:
    app: binance-data-extractor
    component: data-extraction
    version: VERSION_PLACEHOLDER
data:
  # Binance API configuration
  BINANCE_API_URL: "https://api.binance.com"
  BINANCE_FUTURES_API_URL: "https://fapi.binance.com"
  DEFAULT_SYMBOLS: "BTCUSDT,ETHUSDT,BNBUSDT"

  # Database configuration
  DB_ADAPTER: "mysql"
  DB_BATCH_SIZE: "1000"

  # Extraction settings
  MAX_WORKERS: "4"
  LOOKBACK_HOURS: "24"
  API_RATE_LIMIT: "1200"
  API_TIMEOUT: "30"

  # Health check settings
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "5"
  HEALTH_CHECK_PORT: "8080"

  # Performance monitoring
  ENABLE_METRICS: "true"
  METRICS_INTERVAL: "60"

  # Error handling
  MAX_RETRIES: "3"
  RETRY_BACKOFF_SECONDS: "1.0"
  RETRY_BACKOFF_MULTIPLIER: "2.0"
