---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-binance-data-extractor
  namespace: petrosa-apps
  labels:
    app: binance-data-extractor
    component: data-extraction
    version: VERSION_PLACEHOLDER
spec:
  replicas: 2
  selector:
    matchLabels:
      app: binance-data-extractor
      component: data-extraction
  template:
    metadata:
      labels:
        app: binance-data-extractor
        component: data-extraction
        version: VERSION_PLACEHOLDER
      annotations:
        instrumentation.newrelic.com/inject-python: "true"
    spec:
      restartPolicy: Always
      containers:
      - name: data-extractor
        image: yurisa2/petrosa-binance-data-extractor:VERSION_PLACEHOLDER
        imagePullPolicy: Always
        command:
        - opentelemetry-instrument
        - python
        - -m
        - jobs.extract_klines_production
        env:
        - name: BINANCE_API_URL
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: BINANCE_FUTURES_API_URL
        - name: BINANCE_FUTURES_API_URL
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: BINANCE_FUTURES_API_URL
        - name: DEFAULT_SYMBOLS
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: DEFAULT_SYMBOLS


        - name: ENABLE_OTEL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: ENABLE_OTEL
        - name: OTEL_SERVICE_VERSION
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: OTEL_SERVICE_VERSION
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=binance-data-extractor,service.version=VERSION_PLACEHOLDER"
        - name: OTEL_METRICS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: OTEL_METRICS_EXPORTER
        - name: OTEL_TRACES_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: OTEL_TRACES_EXPORTER
        - name: OTEL_LOGS_EXPORTER
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: OTEL_LOGS_EXPORTER
        - name: MAX_WORKERS
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: MAX_WORKERS
        - name: LOOKBACK_HOURS
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: LOOKBACK_HOURS
        - name: API_RATE_LIMIT
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: API_RATE_LIMIT
        - name: API_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: API_TIMEOUT
        - name: API_RATE_LIMIT_PER_MINUTE
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: API_RATE_LIMIT_PER_MINUTE
        - name: REQUEST_DELAY_SECONDS
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: REQUEST_DELAY_SECONDS
        - name: MIN_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: MIN_BATCH_SIZE
        - name: MAX_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: petrosa-binance-data-extractor-config
              key: MAX_BATCH_SIZE
        - name: MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: MYSQL_URI
        - name: DB_ADAPTER
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: DB_ADAPTER
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: petrosa-sensitive-credentials
              key: LOG_LEVEL
        - name: NATS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_ENABLED
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_URL
        - name: NATS_SUBJECT_PREFIX
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_SUBJECT_PREFIX
        - name: NATS_SUBJECT_PREFIX_PRODUCTION
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_SUBJECT_PREFIX_PRODUCTION
        - name: NATS_SUBJECT_PREFIX_GAP_FILLER
          valueFrom:
            configMapKeyRef:
              name: petrosa-common-config
              key: NATS_SUBJECT_PREFIX_GAP_FILLER
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
