apiVersion: batch/v1
kind: Job
metadata:
  name: binance-extractor-manual-job
  namespace: petrosa-apps
  labels:
    app: binance-extractor
    component: manual-job
    type: klines
spec:
  # Allow 3 retries on failure
  backoffLimit: 3
  
  # Clean up completed job after 1 hour
  ttlSecondsAfterFinished: 3600
  
  # Job timeout (30 minutes)
  activeDeadlineSeconds: 1800
  
  template:
    metadata:
      labels:
        app: binance-extractor
        component: manual-job
    spec:
      restartPolicy: Never
      
      containers:
      - name: binance-extractor
        image: DOCKERHUB_USERNAME/petrosa-binance-extractor:latest
        imagePullPolicy: Always
        
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Environment variables
        env:
        - name: BINANCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: binance-api-secret
              key: api-key
        - name: BINANCE_API_SECRET
          valueFrom:
            secretKeyRef:
              name: binance-api-secret
              key: api-secret
        - name: MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mysql-uri
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: ENVIRONMENT
          value: "production"
        
        # Command to run the production extractor
        command:
        - python
        - -m
        - jobs.extract_klines_production
        
        args:
        - --period=15m
        - --symbols=BTCUSDT,ETHUSDT,BNBUSDT
        - --max-workers=3
        - --db-adapter=mysql
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      
      # Pod security context
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000

---
# Example: Simple test job with Python
apiVersion: batch/v1
kind: Job
metadata:
  name: python-test-job
  namespace: petrosa-apps
  labels:
    app: binance-extractor
    component: test-job
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600  # Clean up after 10 minutes
  
  template:
    metadata:
      labels:
        app: binance-extractor
        component: test-job
    spec:
      restartPolicy: Never
      
      containers:
      - name: python-test
        image: python:3.11-slim
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        
        command:
        - python
        - -c
        - |
          import datetime
          import os
          print(f"🎉 Hello from Kubernetes Job!")
          print(f"⏰ Current time: {datetime.datetime.now()}")
          print(f"🐍 Python version: {os.sys.version}")
          print(f"🏠 Hostname: {os.uname().nodename}")
          print("✅ Job completed successfully!")
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
