apiVersion: batch/v1
kind: CronJob
metadata:
  name: binance-klines-m15-production
  namespace: petrosa-apps
  labels:
    app: binance-extractor
    component: klines-extractor
    interval: m15
    version: production
spec:
  # Run every 15 minutes to keep data fresh
  schedule: "*/15 * * * *"
  
  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  # Don't run concurrent jobs to avoid conflicts
  concurrencyPolicy: Forbid
  
  # Allow 10 minutes for job to complete
  activeDeadlineSeconds: 600
  
  jobTemplate:
    metadata:
      labels:
        app: binance-extractor
        component: klines-extractor
        interval: m15
    spec:
      # Retry failed jobs up to 2 times
      backoffLimit: 2
      
      # Clean up completed jobs after 1 hour
      ttlSecondsAfterFinished: 3600
      
      template:
        metadata:
          labels:
            app: binance-extractor
            component: klines-extractor
        spec:
          restartPolicy: Never
          
          # Service account for database access (if needed)
          # serviceAccountName: binance-extractor
          
          containers:
          - name: klines-extractor
            image: DOCKERHUB_USERNAME/petrosa-binance-extractor:latest
            imagePullPolicy: Always
            
            command:
            - python
            - -m
            - jobs.extract_klines_production
            
            args:
            - --period=15m
            - --max-workers=10
            - --db-adapter=mysql
            
            # Environment variables
            env:
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-key
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-secret
            - name: MYSQL_URI
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-uri
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_FORMAT
              value: "json"
            - name: ENVIRONMENT
              value: "production"
            
            # Resource limits
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            
            # Health checks
            livenessProbe:
              exec:
                command:
                - python
                - -c
                - "import sys; sys.exit(0)"
              initialDelaySeconds: 30
              periodSeconds: 60
              timeoutSeconds: 10
              failureThreshold: 3
          
          # Optional: Use specific node selector for data processing
          # nodeSelector:
          #   workload-type: data-processing
          
          # Optional: Tolerations for dedicated nodes
          # tolerations:
          # - key: "workload-type"
          #   operator: "Equal"
          #   value: "data-processing"
          #   effect: "NoSchedule"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: binance-klines-h1-production
  namespace: petrosa-apps
  labels:
    app: binance-extractor
    component: klines-extractor
    interval: h1
    version: production
spec:
  # Run every hour at minute 5 to avoid conflicts with 15m job
  schedule: "5 * * * *"
  
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  activeDeadlineSeconds: 900  # 15 minutes for hourly job
  
  jobTemplate:
    metadata:
      labels:
        app: binance-extractor
        component: klines-extractor
        interval: h1
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 3600
      
      template:
        metadata:
          labels:
            app: binance-extractor
            component: klines-extractor
        spec:
          restartPolicy: Never
          
          containers:
          - name: klines-extractor
            image: DOCKERHUB_USERNAME/petrosa-binance-extractor:latest
            imagePullPolicy: Always
            
            command:
            - python
            - -m
            - jobs.extract_klines_production
            
            args:
            - --period=1h
            - --max-workers=8
            - --db-adapter=mysql
            
            env:
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-key
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-secret
            - name: MYSQL_URI
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-uri
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_FORMAT
              value: "json"
            - name: ENVIRONMENT
              value: "production"
            
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: binance-klines-d1-production
  namespace: petrosa-apps
  labels:
    app: binance-extractor
    component: klines-extractor
    interval: d1
    version: production
spec:
  # Run daily at 00:10 UTC
  schedule: "10 0 * * *"
  
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  activeDeadlineSeconds: 1800  # 30 minutes for daily job
  
  jobTemplate:
    metadata:
      labels:
        app: binance-extractor
        component: klines-extractor
        interval: d1
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 7200  # Keep for 2 hours
      
      template:
        metadata:
          labels:
            app: binance-extractor
            component: klines-extractor
        spec:
          restartPolicy: Never
          
          containers:
          - name: klines-extractor
            image: DOCKERHUB_USERNAME/petrosa-binance-extractor:latest
            imagePullPolicy: Always
            
            command:
            - python
            - -m
            - jobs.extract_klines_production
            
            args:
            - --period=1d
            - --max-workers=5
            - --db-adapter=mysql
            
            env:
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-key
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-api-secret
                  key: api-secret
            - name: MYSQL_URI
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-uri
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_FORMAT
              value: "json"
            - name: ENVIRONMENT
              value: "production"
            
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
