apiVersion: v1
kind: Pod
metadata:
  name: mysql-connectivity-test
  namespace: petrosa-apps
  labels:
    app: mysql-test
spec:
  containers:
  - name: test-container
    image: python:3.11-slim
    command: ["sleep", "3600"]
    env:
    - name: MYSQL_URI
      valueFrom:
        secretKeyRef:
          name: petrosa-sensitive-credentials
          key: MYSQL_URI
    - name: DB_ADAPTER
      valueFrom:
        secretKeyRef:
          name: petrosa-sensitive-credentials
          key: DB_ADAPTER
    - name: ENVIRONMENT
      valueFrom:
        secretKeyRef:
          name: petrosa-sensitive-credentials
          key: ENVIRONMENT
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  restartPolicy: Never
